### ISSUE TITLE
Failed install v0.1.5

### ISSUE THREAD

**Issue by lizdodd** [glennmckechnie/weewx-uradmon#4]
```
$ wget https://github.com/glennmckechnie/weewx-uradmon/archive/v0.1.5.tar.gz
--2020-06-15 21:07:00--  https://github.com/glennmckechnie/weewx-uradmon/archive/v0.1.5.tar.gz

snip
Saving to: ‘v0.1.5.tar.gz’

v0.1.5.tar.gz           [  <=>               ] 292.95K   929KB/s    in 0.3s    

2020-06-15 21:07:02 (929 KB/s) - ‘v0.1.5.tar.gz’ saved [299980]
```

```
$ sudo wee_extension install /home/liz/v0.1.5.tar.gz 
Traceback (most recent call last):
  File "/usr/share/weewx/wee_extension", line 88, in <module>
    main()
  File "/usr/share/weewx/wee_extension", line 67, in main
    config_path, config_dict = weecfg.read_config(options.config, _args)
  File "/usr/share/weewx/weecfg/__init__.py", line 173, in read_config
    locations=locations, file_name=file_name)
  File "/usr/share/weewx/weecfg/__init__.py", line 147, in find_file
    raise IOError("%s is not a file" % file_path)
IOError: install is not a file
```
I'm not sure what is the problem, and the error message isn't really useful. Can anyone suggest a solution?

**Comment by glennmckechnie** [comment]
Just checked the file and it downloads and installs okay here.

AhHa; use  --install, not install 
wee_extension --install v0.1.5.tar.gz

**Comment by lizdodd** [comment]
Thanks for that, I think Homer Simpson had a special phrase for that type of error.
I then was caught by not knowing my unit number. I was thinking that I needed to restart weeWx before the changes took effect, but that was not so. Logging in to uradmon was needed to find my unit number.
